project_id = "meksngtchwwkoaycygxy"

[functions.publish-to-wordpress]
verify_jwt = true

[functions.test-wordpress-connection]
verify_jwt = true

[functions.create-pseo-project]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.fetch-airtable-schema]
verify_jwt = false

[functions.create-project-record]
verify_jwt = true

[functions.setup-subaccount-airtable]
verify_jwt = true

[functions.get-airtable-field-options]
verify_jwt = true

[functions.get-article-status]
verify_jwt = true

[functions.create-airtable-article]
verify_jwt = true

[functions.fetch-airtable-articles]
verify_jwt = true

[functions.update-airtable-article]
verify_jwt = true

[functions.trigger-n8n-workflow]
verify_jwt = true

[functions.test-airtable-connection]
verify_jwt = true

[functions.invite-team-member]
verify_jwt = true

[functions.create-agency-invite]
verify_jwt = true

[functions.accept-agency-invite]
verify_jwt = false

[functions.invite-subaccount-client]
verify_jwt = true

[functions.accept-subaccount-invite]
verify_jwt = false

[functions.upgrade-to-agency]
verify_jwt = true

[functions.create-transfer-request]
verify_jwt = true

[functions.handle-transfer-request]
verify_jwt = true

[functions.invite-agency-member]
verify_jwt = true
