project_id = "meksngtchwwkoaycygxy"

[functions.publish-to-wordpress]
verify_jwt = true

[functions.test-wordpress-connection]
verify_jwt = true

[functions.create-pseo-project]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.fetch-airtable-schema]
verify_jwt = false

[functions.create-project-record]
verify_jwt = true

[functions.setup-subaccount-airtable]
verify_jwt = true

[functions.get-airtable-field-options]
verify_jwt = true
